###
# connectivity-manager
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: connectivity-manager
  name: connectivity-manager
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: connectivity-manager
  template:
    metadata:
      labels:
        cluster: management
        component: connectivity-manager
    spec:
      containers:
      - name: connectivity-manager
        image: __NPH_REGISTRY/__NPH_REGISTRY_NAMESPACE/connectivity-manager:__NPH_VERSION
        imagePullPolicy: Always
        args:
          - "run"
          - "--debug"
          - "--port=8383"
          - "--systemModelAddress=system-model.__NPH_NAMESPACE:8800"
          - "--queueAddress=broker.__NPH_NAMESPACE:6650"
          - "--offlinePolicy=drain"
          - "--threshold=1m"
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
